### ISSUE TITLE
Dark Theme to ProgressDialog

### ISSUE THREAD

**Issue by VishnuSanal** [VishnuSanal/Quotes#1]
**Describe the bug**

Currently, the Android dark mode does not reflect on `ProgressDialogs` across the app

**To Reproduce**

1. Click on the menu icon
2. - Click on BG Pick icon -> Click on Default Images OR
    - Click on the Font Pick icon
4. See the `ProgressDialog` in light theme regardless of Android's dark mode

**Expected behavior**

Android dark mode updates reflect on `ProgressDialog` too

**Screenshots**

![SS](https://user-images.githubusercontent.com/50027064/119669761-eea1a280-be55-11eb-8f78-61e91f47fe12.jpg)

**Additional context**

The file to work with will be `MainActivity.java` and the `ProgressDialog` objects are `bgDialog` & `fontDialog`

**Comment by danger-ahead** [comment]
Hi! I can fix this issue.
Will start working on it ASAP.
Kindly consider assigning me :)

**Comment by danger-ahead** [comment]
@VishnuSanal I've opened a PR with the fix. Kindly have a look.

**Comment by VishnuSanal** [comment]
> @VishnuSanal I've opened a PR with the fix. Kindly have a look.

@danger-ahead Thank you for your time & efforts. Will look into it in a while :)
