### ISSUE TITLE
Material you theme in the app

### ISSUE THREAD

**Issue by zoroya1** [VishnuSanal/Quotes#119]
**Is your feature request related to a problem? Please describe.**

It will be nice if app uses material you theme, which adapts the app colour to wallpaper colour 

**Describe the solution you'd like**

Foreground or certain elements of the app in material you logic

**Describe alternatives you've considered**

Changing theme from built in wallpapers are good but material you theme logic will give it more polished and minimal, eye pleasant look

**Additional context**

**Comment by VishnuSanal** [comment]
please track with #90. closing this due to the existence of a similar issue
