### ISSUE TITLE
Feature Request: separate custom created quotes tab | search | some minor improvements

### ISSUE THREAD

**Issue by shuvashish76** [VishnuSanal/Quotes#12]
**Is your feature request related to a problem? Please describe.**

1. separate custom created Quotes tab (which will help to find such Quotes easily)
2. search feature (search a word to find related Quotes from Favourite/Custom_created Quotes)
3. Minor improvements

**Describe the solution you'd like**

**Custom created Quotes tab**
when we click on Fronts it appears like this
![Screenshot_2021-06-13-04-20-13](https://user-images.githubusercontent.com/48226312/121790735-fefca000-cbff-11eb-8c96-8668183b985d.jpeg)
something similar to the Favourite section👇
![Screenshot_2021-06-13-04-19-20](https://user-images.githubusercontent.com/48226312/121790800-c14c4700-cc00-11eb-9c65-4ed995a27c1f.jpeg)
- if the user clicks on create new quote option once it should open up quotes created by the user. If click on the same icon again it should show an option to create quotes, (both _`Custom_created quotes/Create new Quote`_ function in one button)

---
**Search option**
![Screenshot_2021-06-13-04-59-30](https://user-images.githubusercontent.com/48226312/121791181-ae3b7600-cc04-11eb-8974-e5177301459f.jpeg)

as for share & delete, we are moving towards swipe left/right, we don't need those share & delete button next to a fav quote #8

https://user-images.githubusercontent.com/48226312/121791423-45093200-cc07-11eb-9a15-a8eb840ba3b9.mp4

what about after searching some particular word, search show Quotes like these. which quotes are from favourites & which are created.
ex: (for example purpose there is no particular word matching in all quotes)

![Screenshot_2021-06-13-04-59-30 jpeg](https://user-images.githubusercontent.com/48226312/121791620-8a2e6380-cc09-11eb-98b1-d1ba31217baa.png)
---
**Other minor improvements**
![Screenshot_2021-06-09-15-06-40](https://user-images.githubusercontent.com/48226312/121790928-218fb880-cc02-11eb-9145-93b97a2cc25a.jpeg)

in current version
- no1 & no2 does nothing. no3 & no5 does the same function "Go Home" which is unnecessary

according to my idea
- now no1 & no2 now both function separately
- if we make a tabbed version as I mentioned then for Favourite tab (no1) there is no need for no3 & no4 button.
- & for Create new Quote button (no2), no4 should function as the current version but no need for the Cancel (no3) button as clicking no2 function as both  _`Custom created quotes/Create new Quote`_

**Comment by VishnuSanal** [comment]
1. We can use an option like tagging on top of the favourites screen to achieve the same result (on the new layout) IMO @shuvashish76 What do you think? Please track with #23 (discussions too)
2. Search feature - please track with #24
3. A small indicator on whether the Quote is added manually or not (which will be redundant since the user can achieve the same result by using the _tag_

4. All these are a part of our old layout - please revisit :)
