### ISSUE TITLE
Multiple Select & Sort

### ISSUE THREAD

**Issue by shuvashish76** [VishnuSanal/Quotes#16]
- Multiple select for deleting or pinning
 - Sort pinned quotes manually

[Example video](https://user-images.githubusercontent.com/48226312/123503195-0b0c4700-d66f-11eb-9878-2cb405489d41.mp4)

**Comment by shuvashish76** [comment]
I forgot we don't have pinned Quotes feature yet 🤦‍♂️

**Comment by VishnuSanal** [comment]
Closing since this is highly related to #12 :)
