### ISSUE TITLE
Tagging Feature

### ISSUE THREAD

**Issue by VishnuSanal** [VishnuSanal/Quotes#18]
**Is your feature request related to a problem? Please describe.**
Implement tagging feature as shown in the screenshot

![image](https://user-images.githubusercontent.com/50027064/123505119-e322e080-d67a-11eb-90dc-c881e2f36619.png)

**Additional Info**

Copied from [Telegram Group](t.me/QuotesStatusCreator) as suggested by @shuvashish76

**Comment by shuvashish76** [comment]
inspired from: https://1lib.in/blog/12
screenshot source: https://1lib.in/
