### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by VishnuSanal** [VishnuSanal/Quotes#26]
A provision to change the font size by the user

**Comment by shuvashish76** [comment]
Plus it would be nice to have common formatting options like Bold, Italic, Underline, Strikethrough, Monospace while adding custom quotes.

![Untitled](https://user-images.githubusercontent.com/48226312/128650921-c7d13f27-3e48-41ca-87e1-4c43bd144202.png)

Screenshot from Telegram Desktop but there is a similar popup view while we edit text on android Telegram.

**Comment by VishnuSanal** [comment]
> Plus it would be nice to have common formatting options like Bold, Italic, Underline, Strikethrough, Monospace while adding custom quotes.

@shuvashish76 Please create a new issue for this :)
