### ISSUE TITLE
Font size not reflecting on 'Save to Gallery'

### ISSUE THREAD

**Issue by VishnuSanal** [VishnuSanal/Quotes#31]
The font size do not reflect when the save to gallery option is used

**Comment by TemitopeAgbaje** [comment]
can i work on this

**Comment by VishnuSanal** [comment]
> can i work on this
> 

Sure, go ahead!

**Comment by TemitopeAgbaje** [comment]
Hi, Pleas how do i go about with this..I am abit confused cos i am never worked with java

**Comment by VishnuSanal** [comment]
@TemitopeAgbaje Hello!  The font size is implemented for the share feature. The issue essentially demands to implement that to the save feature too.

i.e, the font size is implemented in shareImage function & you'd need to implement the same for saveImage too. The file concerned is ExportHelper.java.

**Comment by VishnuSanal** [comment]
@TemitopeAgbaje Any updates here? Thanks!

**Comment by VishnuSanal** [comment]
> @TemitopeAgbaje Any updates here? Thanks!

@TemitopeAgbaje This will be taken over if there's no response within 12 hours.

**Comment by VishnuSanal** [comment]
> @TemitopeAgbaje Any updates here? Thanks!

@TemitopeAgbaje This will be taken over if there's no response within 12 hours from now.

**Comment by TemitopeAgbaje** [comment]
Hi @VishnuSanal  I have not been able to look into it.
Please could you assign it to another person. 
Apologies for my late response.
