### ISSUE TITLE
Share this app on About

### ISSUE THREAD

**Issue by VishnuSanal** [VishnuSanal/Quotes#46]
Share this app option on about section that helps the user share the app with following text

Quotes Status Creator lets you share quotations as status images on social media. Get it at kutt.it/Quotes

**Comment by Devansh-gaur-1611** [comment]
Hi @VishnuSanal, I want to contribute to this issue. Can u give me a brief understanding of what are the pre-requisites for solving this issue?
However, I know how to send an image or a link using the command(Intent.ACTION_SEND) but I have no idea how to send an app so I want your guidance for this

**Comment by VishnuSanal** [comment]
Devansh-gaur-1611 Hello! Please see your answers in order.

> Hi @VishnuSanal, I want to contribute to this issue. Can u give me a brief understanding of what are the pre-requisites for solving this issue?

I didn't quite get your question. The pre requisites would be usual Android Dev. Since, you're already a contributor, it won't be much of a hassle :)

> However, I know how to send an image or a link using the command(Intent.ACTION_SEND) but I have no idea how to send an app so I want your guidance for this

Oops! I just meant to share the following text from About. Please add one more item to About after "Rate the App" that shares the following text. PS: Sorry for not clarifying it in the issue!

```
Install Quotes Status Creator - an open source app that lets you share quotations as status images on social media\n\nhttps://play.google.com/store/apps/details?id=phone.vishnu.quotes
```
Use:
title: Share the App
desc: Share Quotes Status Creator with your friends
Use the share image as the icon

Furthermore, join our community [here](t.me/QuotesStatusCreator) if you have any queries or just to get in touch :) Commenting here would be okay too!

**Comment by Devansh-gaur-1611** [comment]
Thanks for the answer and assigning me this🥳.I will start working on this issue from now itself.👍

**Comment by Devansh-gaur-1611** [comment]
Hi @VishnuSanal, I have created a pull request for this issue. But when I have created a pull request,it is showing a cross sign,can u please help me what should I have to do
![issue](https://user-images.githubusercontent.com/89275109/135563775-413d07b2-35c0-4594-9c25-16ed52028fef.png)

**Comment by VishnuSanal** [comment]
> Hi @VishnuSanal, I have created a pull request for this issue. But when I have created a pull request,it is showing a cross sign,can u please help me what should I have to do

Let's talk about PR on the PR section! Help sent :)
