### ISSUE TITLE
Unsplash API for photos

### ISSUE THREAD

**Issue by shuvashish76** [VishnuSanal/Quotes#53]
https://unsplash.com/

Checkout these apps
- [Mysplash](https://github.com/WangDaYeeeeee/Mysplash) available on F-Droid, project archived though
- [Resplash](https://github.com/b-lam/Resplash), available on Izzy repo, active project

I think both apps use unsplash api & fetch images from there. Similarly can we use unsplash api?

Benefits:
- thousands of free high quality photos
- daily new updated photos
- search topics according to your choice
- possibility to add this app to F-Droid main repo
- no firebase dependencies
etc...

Unsplash license:
https://unsplash.com/license

Unsplash API:
https://unsplash.com/developers
https://unsplash.com/documentation

https://unsplash.com/api-terms

**Comment by VishnuSanal** [comment]
Fixed!
