### ISSUE TITLE
Continuous Undo function

### ISSUE THREAD

**Issue by shuvashish76** [VishnuSanal/Quotes#59]
- show "Undo X" "Undo Y" etc when user remove multiple quotes from favorite section between [1.5 sec](https://github.com/VishnuSanal/Quotes/blob/master/app/src/main/java/phone/vishnu/quotes/fragment/FavoriteFragment.java#L372)
- popup message should remain open till you keep deleting quotes from favorites & it should get removed iff you stop more than 1.5+ sec

**Comment by VishnuSanal** [comment]
I think this will be too much for our app. This will be cumbersome UX too, IMO.
