### ISSUE TITLE
Fastlane structures implemented

### ISSUE THREAD

**Issue by VishnuSanal** [VishnuSanal/Quotes#68]
Ping @IzzySoft

Also, the screenshots are not added right now. I have nothing to change, still should those be added? Will this break the current screenshots that's live right now?

I tried adding the same ones I use for Play Store, but the [tests fail](https://github.com/VishnuSanal/Quotes/actions/workflows/release-workflow.yml) & shows issues with aspect ratio. So, is it okay to have fastlane structures without screenshots & feature graphic?

Or should I download the current assets that are live [here](https://apt.izzysoft.de/fdroid/index/apk/phone.vishnu.quotes) and add it to the repo?

Waiting for your confirmation to create the tag. Thanks! :)

**Comment by IzzySoft** [comment]
> Will this break the current screenshots that's live right now?

There won't be any screenshots at F-Droid as there are none in your Fastlane structure. I don't know nothing about what your tests do (I'm not even an Android dev), so I cannot tell.

The minimum Fastlane is set up and acceptable by F-Droid, you even built upon it and added some more – so for your RFP it should be sufficient. But without screenshots in Fastlane there won't be screenshots in F-Droid.

Looking at the workflow errors: Did you really try to add thumbnails instead of screenshots? 189px is indeed quite small. No idea with the featureGraphic, though.

**Comment by VishnuSanal** [comment]
> I don't know nothing about what your tests do (I'm not even an Android dev), so I cannot tell.

I meant [this](https://github.com/ashutoshgngwr/validate-fastlane-supply-metadata) GitHub action to validate fastlane fails (that I saw you mention [here](https://gitlab.com/-/snippets/1895688)) - sorry for not clarifying.
 
> The minimum Fastlane is set up and acceptable by F-Droid, you even built upon it and added some more – so for your RFP it should be sufficient. But without screenshots in Fastlane there won't be screenshots in F-Droid.

I was mentioning about IzzyOnDroid. This app is not yet eligible for F-Droid **yet**.

> Looking at the workflow errors: Did you really try to add thumbnails instead of screenshots? 189px is indeed quite small. No idea with the featureGraphic, though.

`Error: 'max:min' edge radio should be at most 2.0: got=2.14`

I got this error at first, so I was trying to fix it ;)

Anyways, I added screenshots & feature graphic back, the workflow doesn't seem to accept those now too (gives the same error). Will this be a problem for your (IzzyOnDroid's) indexer to pull from my repo?

Thanks! - Vishnu

**Comment by IzzySoft** [comment]
Ah, now. OK, consider those Fastlane checkers you use with the Github actions as running in "strict mode", while we are happy with "compatibility mode". My repo has an "upper cap", so the process pulling files from Fastlane takes care to downsize if larger (smallest side not wider than 350px, compress, if needed convert to JPG). So no worries. Not sure what F-Droid itself checks, but there it's rather my downsizing being skipped than more checks being added.

> I was mentioning about IzzyOnDroid. This app is not yet eligible for F-Droid yet.

Adding it right now. Some notes while checking:

* `short_description.txt`: No need to repeat the app name. ShortDesc is always displayed next to the app name or title. So I'd suggest shortening that to `share quotations as status images on social media` – keep it crisp :wink:
* `full_description.txt`: I'd leave out those emoticons, they are prone to break things. I'll ignore that for now and still accept it as-is; please make sure to check how it looks on my site once the next release was pulled and see if it's allright. Apart from that technical reason: overdoing it makes it look less serious – and you are using quite many :wink:
* screenshots: please keep in mind that most users browse the app collection on their phones, so the framing mostly wastes precious screen estate. Removing the frames might also solve the errors from your Github workflow (just tested: only if you cut a little from the height as well; with framing it's 2.14, without 2.1)

> Or can I just ignore the workflow's result?

You probably can, yes, and most people won't notice. They seem to be good guidance, though: An aspect ratio higher than 1:2 is hard to look at (looks unnatural).

**Comment by shuvashish76** [comment]
[izzyrepo](https://apt.izzysoft.de/fdroid/index/apk/phone.vishnu.quotes) missed latest [v2.7.0](https://github.com/VishnuSanal/Quotes/releases/tag/V2.7.0).
Some Fastlane issues @IzzySoft ?

**Comment by IzzySoft** [comment]
No. Some naming issue, check your tag (hint: CaseSensitivity).

**Comment by VishnuSanal** [comment]
> No. Some naming issue, check your tag (hint: CaseSensitivity).

Oh, yes. Updated now.

> [izzyrepo](https://apt.izzysoft.de/fdroid/index/apk/phone.vishnu.quotes) missed latest [v2.7.0](https://github.com/VishnuSanal/Quotes/releases/tag/V2.7.0). Some Fastlane issues @IzzySoft ?

Thanks for noticing that & reporting it :)

**Comment by IzzySoft** [comment]
Then v2.7.0 should show up in about an hour :smiley:

**Comment by IzzySoft** [comment]
And there it is :smile:
