### ISSUE TITLE
Undo Delete on Favourites

### ISSUE THREAD

**Issue by shuvashish76** [VishnuSanal/Quotes#7]
**Is your feature request related to a problem? Please describe.**
Currently, there is no option to undo a deleted Quote if the user delete a quote mistakenly

**Describe the solution you'd like**
probably something like a popup message (for 5-7sec) to undo deleted Quote will be useful.

**Additional context**
examples from Gmail undo Archive/Delete feature

![Capture](https://user-images.githubusercontent.com/48226312/121523353-bda79d00-ca13-11eb-8f78-95c2f23a2594.PNG)
![Capture1](https://user-images.githubusercontent.com/48226312/121523375-c26c5100-ca13-11eb-8aeb-555c6fa93ee4.PNG)
![Screenshot_2021-06-10-17-34-55](https://user-images.githubusercontent.com/48226312/121523439-d748e480-ca13-11eb-8a7f-7f4f846fc148.jpeg)

**Comment by VishnuSanal** [comment]
@shuvashish76 Actually favourites' is under a complete overhaul to RecyclerView with SQLite (Room) & MVVM. The current layout uses the old ListView. So, undo will get implemented along with that update :)

**Comment by VishnuSanal** [comment]
As mentioned in the previous comment, Favorites' Screen got a complete overhaul & we are having swipe to delete (& share) on it. So, the possibility to get deleted by mistake is far less. This feature is always good to have, but not so urgent to implement IMO - so making it `priority-low` :)
