### ISSUE TITLE
Weird ACRA behaviour

### ISSUE THREAD

**Issue by VishnuSanal** [VishnuSanal/Quotes#75]
ACRA doesn't capture the error when the crash happens for the first time. It only captures from the second time. If the app is cleared from recents and opened again, the same behavior repeats.

I assume this has something to do with ACRA not getting initialized when the first crash happens. Maybe, I'm missing something silly!

Crash reporting works for now, but not completely. Only recurring crashes can be captured as of now.

Any help will be appreciated. Thanks!

**Comment by IzzySoft** [comment]
Speaking of which: ACRA changed its behaviour. In the past it was opt-in by default, now it is [sending silent reports](https://www.acra.ch/docs/Interactions) without asking the user's consent. Can you please check how you've configured it? Will the user be asked?

**Comment by IzzySoft** [comment]
@VishnuSanal can you give a short status message on this? I'm not a dev, but if I read the code correctly, reports will only be sent if the user actively [presses a button](https://github.com/VishnuSanal/Quotes/blob/ff272001adc1a1d41793412160631536d42ad5aa/app/src/main/java/phone/vishnu/quotes/acra/ACRAErrorActivity.java#L144) deciding whether the report should go via Telegram or via Github. Can you confirm that? So no other "silent reports behind the user's back"?

**Comment by VishnuSanal** [comment]
@IzzySoft Yes.

The user should click the button for the report to be sent.

(and very sorry for the delay, was lil caught up & wanted to check their docs thoroughly before replying to you - just to be sure!)

**Comment by IzzySoft** [comment]
Thanks! Especially for making sure (delay gladly accepted for that, your re-opening already told me you're on it). Whitelisted then, so no Anti-Feature will be raised :smiley: :partying_face:

**Comment by VishnuSanal** [comment]
@shuvashish76 Sure, will look into it.

> since it phone home by default.

Didn't get you...?

**Comment by VishnuSanal** [comment]
@IzzySoft

> @VishnuSanal [see here](https://www.acra.ch/docs/Interactions) – default behavior of ACRA now is sending silent crash reports –

Yes, saw that!

> i.e. the user is not asked for consent and not even informed about the fact, (crash) reports are simply sent in the background unless you explicitly specify differently in your code.

I wonder where or how this gets sent (in the case of Quotes). I use a [custom sender that opens an activity](https://github.com/VishnuSanal/Quotes/blob/459afaa3527ec7b482f7f009b382d62eaa1ce15f/app/src/main/java/phone/vishnu/quotes/acra/ACRASender.java#L31) where the error is displayed to the user. Then, [as you mentioned previously](https://github.com/VishnuSanal/Quotes/issues/75#issuecomment-1200157083), the user can choose to ignore it or to send it by pressing one of the two buttons provided (GItHub & Telegram). I assume the role played by ACRA ends where it opens `ACRAErrorActivity` since sending is handled by the app itself.

> Scanners can detect the presence of ACRA automatically, but not the configuration – hence ACRA is now considered a tracker (also with my repo and F-Droid, though we can white-list it as we "serve" the app in question; AM just scans "some app" and cannot know about the background, so it will always yield the warning).

Please correct me whether my assumption above is wrong, or kindly white-list Quotes from the warning ;)

Thanks!

**Comment by IzzySoft** [comment]
> > unless you explicitly specify differently in your code

> I use a [custom sender that opens an activity](https://github.com/VishnuSanal/Quotes/blob/459afaa3527ec7b482f7f009b382d62eaa1ce15f/app/src/main/java/phone/vishnu/quotes/acra/ACRASender.java#L31)

I'd say a "custom sender" qualifies as "explicitly specifying differently", wouldn't you agree? So we're back at the point where I was saying I see no need to remove ACRA entirely – unless you want to make sure no scanner reports it erroneously as "tracking!" because it just looks at the "signature" (like AM which was named above, as it cannot have a "negative list" for all apps).

> or kindly white-list Quotes from the warning

See [above](https://github.com/VishnuSanal/Quotes/issues/75#issuecomment-1200237916) – done already 3 days ago :smiley:

**Comment by VishnuSanal** [comment]
> I'd say a "custom sender" qualifies as "explicitly specifying differently", wouldn't you agree?

Yups, agreed. My bad!

> > or kindly white-list Quotes from the warning
> 
> See [above](https://github.com/VishnuSanal/Quotes/issues/75#issuecomment-1200237916) – done already 3 days ago :smiley:

:D thanks
