### ISSUE TITLE
Better Share & Delete icon

### ISSUE THREAD

**Issue by shuvashish76** [VishnuSanal/Quotes#8]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [I click on the share/delete icon from my favourite Quotes section because both icons are too close. I often misclick the Delete icon while clicking on the share icon. Plus if misclicked the Delete icon the Quote is lost (as mentioned here #7)]

current version:
![Screenshot_2021-06-10-16-50-48](https://user-images.githubusercontent.com/48226312/121525141-a23d9180-ca15-11eb-9d5c-8625c5d38caf.jpeg)
![Screenshot_2021-06-10-14-03-49](https://user-images.githubusercontent.com/48226312/121525175-a9fd3600-ca15-11eb-9afc-1120ceebef69.jpeg)

**Describe the solution you'd like**
I think it would be better to make
- both icons bit bigger
- more gap between both icons
- transparent icons (so for big Quotes both icons & quote lines will be clearly visible)

**Describe alternatives you've considered**
for ex:
![Screenshot_2021-06-10-14-03-49](https://user-images.githubusercontent.com/48226312/121525550-1a0bbc00-ca16-11eb-9ef3-506820469349.png)
which will look like this
![Screenshot_2021-06-10-16-50-50](https://user-images.githubusercontent.com/48226312/121525634-34459a00-ca16-11eb-84b0-74bd134d1a9a.jpeg)
![Screenshot_2021-06-10-18-17-10](https://user-images.githubusercontent.com/48226312/121527938-97d0c700-ca18-11eb-8fef-d23a18353935.jpeg)

what I changed:
- both icons bit bigger, more gap between both icons, icons transparency set to 70%, share icon little bit bigger than delete icon, delete icon colour changed to red

PS I'm not a professional logo designer 😅

**Comment by VishnuSanal** [comment]
@shuvashish76 As mentioned on #7 the Favourites' is getting a complete overhaul. Will fix this along with that update :)

PS: I really appreciate your time & efforts to test & report the bugs shortcomings in the app <3

**Comment by VishnuSanal** [comment]
As mentioned in the previous comment, Favorites' Screen got a complete overhaul & we are having swipe to delete (& share) on it. So, in effect this issue is fixed - closing :)
