### ISSUE TITLE
Weblate integration broken

### ISSUE THREAD

**Issue by comradekingu** [VishnuSanal/Quotes#83]
https://hosted.weblate.org/projects/quotes-status-creator/quotes-status-creator/#alerts
>fatal: could not read Username for 'https://github.com': terminal prompts disabled
 (128)

I think I can fix this if you add the user `kingu` in https://hosted.weblate.org/access/quotes-status-creator

**Comment by VishnuSanal** [comment]
> I think I can fix this if you add the user `kingu` in https://hosted.weblate.org/access/quotes-status-creator

Thanks, added you as an admin.

**Comment by comradekingu** [comment]
Changed to 
GitHub instead of Git
https://github.com/VishnuSanal/Quotes.git for the repo and push URL.
`master` branch (since weblate-translations) doesn't exist.

**Comment by VishnuSanal** [comment]
> I think "edit the base-file" should be enabled in https://hosted.weblate.org/settings/quotes-status-creator/quotes-status-creator/#files because then it becomes easier for people to fix the source strings.

Why would/should someone update the source strings? Didn't get what you meant with _fix the source strings_. Thanks.

**Comment by comradekingu** [comment]
@VishnuSanal There are improvements to be made. I will get around to it.
It is quite good, so no worries.

**Comment by VishnuSanal** [comment]
> `master` branch (since weblate-translations) doesn't exist.

I used `weblate-translations` assuming it would commit the changes and won't be PRs. Now I discover changes will be in PRs, I understand my mistake. I didn't check `edit the base-file` because of the same reason too, will change. Thanks for your help :)
