### ISSUE TITLE
UI Redesign - Card , Icons and more

### ISSUE THREAD

**Issue by AyushIyankan** [VishnuSanal/Quotes#90]
As we are changing logo on V3.0.0 release of the Quotes app , the overall colour scheme of UI can be adopted to palette taken from logo colour. The about section icons and older material UI can be replaced by newer icons and elements respectively. Card can be improved both in icons and the home search and tags can be redesigned to a uniform UI design ( overall app ). What's your opinions / comments regarding these? Any suggestions can be drawn below. 🙂

**Comment by VishnuSanal** [comment]
@AyushIyankan Hi! I vote in favour. All your suggestions makes sense & can be done :)

**Comment by shuvashish76** [comment]
I think MD3 switches is a good start.

![152649142-81221cec-4dc0-4ffe-b038-e83c4b16e784](https://user-images.githubusercontent.com/48226312/166647687-6eb9a1e6-0f14-4ecc-ace4-ac1b7600a92e.png)

**Comment by VishnuSanal** [comment]
closing since parts of this are implemented in v3.0.0 & since the ones that aren't can be tracked with #127
